# Rerun of SFU author collection

* Originally were getting 20k+ authors when using author search in OpenAlex
* This script was provided to us by the OpenAlex team
* We are interested in all authors who published with SFU between 2020-2024
* As a sanity check, Scopus lists ~6k SFU authors in this time frame, so we would expect somewhat more authors to be returned here (but <<20k)

In [35]:
import urllib.request, json, urllib.parse 
import requests
import pandas as pd
import ast
from tqdm import tqdm

In [36]:
SFU = "https://openalex.org/I18014758" 
#base = ("https://api.openalex.org/works?" "filter=authorships.institutions.id:I18014758,publication_year:2020-2024" "&select=authorships&per_page=200&mailto=tpa42@sfu.ca") 
base = ("https://api.openalex.org/works?" "filter=authorships.institutions.id:I18014758,publication_year:2020-2024" "&per_page=200&mailto=tpa42@sfu.ca") 
cursor, authors, works = "*", set(), []

while cursor: 
    d = json.load(urllib.request.urlopen(base + "&cursor=" + urllib.parse.quote(cursor))) 
    if not d["results"]: 
        break 
    for w in d["results"]:
        works.append(w)
        for au in w["authorships"]: 
            if SFU in {i["id"] for i in au["institutions"]}: 
                authors.add(au["author"]["id"]) 
    cursor = d["meta"]["next_cursor"]

In [37]:
print(w)

{'id': 'https://openalex.org/W7165396956', 'doi': 'https://doi.org/10.70177/jsa.v1i6.1674', 'title': 'The Impact of Selective Logging on Forest Structure and Function', 'display_name': 'The Impact of Selective Logging on Forest Structure and Function', 'publication_year': 2024, 'publication_date': '2024-12-26', 'ids': {'openalex': 'https://openalex.org/W7165396956', 'doi': 'https://doi.org/10.70177/jsa.v1i6.1674'}, 'language': None, 'primary_location': {'id': 'doi:10.70177/jsa.v1i6.1674', 'is_oa': True, 'landing_page_url': 'https://doi.org/10.70177/jsa.v1i6.1674', 'pdf_url': 'https://research.adra.ac.id/index.php/selvicoltura/article/download/1674/1128', 'source': {'id': 'https://openalex.org/S7407059167', 'display_name': 'Journal of Selvicoltura Asean', 'issn_l': '3048-1171', 'issn': ['3048-1171', '3048-1198'], 'is_oa': False, 'is_in_doaj': False, 'is_core': False, 'host_organization': None, 'host_organization_name': None, 'host_organization_lineage': [], 'host_organization_lineage_names': [], 'type': 'journal'}, 'license': 'cc-by-sa', 'license_id': 'https://openalex.org/licenses/cc-by-sa', 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Journal of Selvicoltura Asean', 'raw_type': 'journal-article'}, 'type': 'article', 'indexed_in': ['crossref'], 'open_access': {'is_oa': True, 'oa_status': 'hybrid', 'oa_url': 'https://research.adra.ac.id/index.php/selvicoltura/article/download/1674/1128', 'any_repository_has_fulltext': False}, 'authorships': [{'author_position': 'first', 'author': {'id': 'https://openalex.org/A5138981126', 'display_name': 'Olivia Davis', 'orcid': None}, 'institutions': [{'id': 'https://openalex.org/I18014758', 'display_name': 'Simon Fraser University', 'ror': 'https://ror.org/0213rcc28', 'country_code': 'CA', 'type': 'education', 'lineage': ['https://openalex.org/I18014758']}], 'countries': ['CA'], 'is_corresponding': False, 'raw_author_name': 'Olivia Davis', 'raw_affiliation_strings': ['Simon Fraser University'], 'raw_orcid': None, 'affiliations': [{'raw_affiliation_string': 'Simon Fraser University', 'institution_ids': ['https://openalex.org/I18014758']}]}, {'author_position': 'middle', 'author': {'id': 'https://openalex.org/A5032434756', 'display_name': 'Ethan Thompson', 'orcid': None}, 'institutions': [{'id': 'https://openalex.org/I192455969', 'display_name': 'York University', 'ror': 'https://ror.org/05fq50484', 'country_code': 'CA', 'type': 'education', 'lineage': ['https://openalex.org/I192455969']}], 'countries': ['CA'], 'is_corresponding': False, 'raw_author_name': 'Ethan Thompson', 'raw_affiliation_strings': ['York University'], 'raw_orcid': None, 'affiliations': [{'raw_affiliation_string': 'York University', 'institution_ids': ['https://openalex.org/I192455969']}]}, {'author_position': 'last', 'author': {'id': 'https://openalex.org/A5139001286', 'display_name': 'Emma Clark', 'orcid': None}, 'institutions': [{'id': 'https://openalex.org/I168635309', 'display_name': 'University of Calgary', 'ror': 'https://ror.org/03yjb2x39', 'country_code': 'CA', 'type': 'education', 'lineage': ['https://openalex.org/I168635309']}], 'countries': ['CA'], 'is_corresponding': False, 'raw_author_name': 'Emma Clark', 'raw_affiliation_strings': ['University of Calgary'], 'raw_orcid': None, 'affiliations': [{'raw_affiliation_string': 'University of Calgary', 'institution_ids': ['https://openalex.org/I168635309']}]}], 'institutions': [], 'countries_distinct_count': 1, 'institutions_distinct_count': 3, 'corresponding_author_ids': [], 'corresponding_institution_ids': [], 'apc_list': None, 'apc_paid': None, 'fwci': 0.0, 'has_fulltext': True, 'cited_by_count': 0, 'citation_normalized_percentile': {'value': 0.40805931, 'is_in_top_1_percent': False, 'is_in_top_10_percent': False}, 'cited_by_percentile_year': None, 'biblio': {'volume': '1', 'issue': '6', 'first_page': '282', 'last_page': '292'}, 'is_retracted': False, 'is_paratext': False, 'is_xpac': False, 'primary_topic': {'id': 'https://openalex.org/T12118', 'display_name': 'Forest Biomass Utilization and Management', 'score': 0.3118000030517578, 'subfield': {'id': 'https://openalex.org/subfields/2211', 'display_name': 'Mechanics of Materials'}, 'field': {'id': 'https://openalex.org/fields/22', 'display_name': 'Engineering'}, 'domain': {'id': 'https://openalex.org/domains/3', 'display_name': 'Physical Sciences'}}, 'topics': [{'id': 'https://openalex.org/T12118', 'display_name': 'Forest Biomass Utilization and Management', 'score': 0.3118000030517578, 'subfield': {'id': 'https://openalex.org/subfields/2211', 'display_name': 'Mechanics of Materials'}, 'field': {'id': 'https://openalex.org/fields/22', 'display_name': 'Engineering'}, 'domain': {'id': 'https://openalex.org/domains/3', 'display_name': 'Physical Sciences'}}, {'id': 'https://openalex.org/T11753', 'display_name': 'Forest Management and Policy', 'score': 0.1071000024676323, 'subfield': {'id': 'https://openalex.org/subfields/2306', 'display_name': 'Global and Planetary Change'}, 'field': {'id': 'https://openalex.org/fields/23', 'display_name': 'Environmental Science'}, 'domain': {'id': 'https://openalex.org/domains/3', 'display_name': 'Physical Sciences'}}, {'id': 'https://openalex.org/T13009', 'display_name': 'Agroforestry and silvopastoral systems', 'score': 0.10610000044107437, 'subfield': {'id': 'https://openalex.org/subfields/1107', 'display_name': 'Forestry'}, 'field': {'id': 'https://openalex.org/fields/11', 'display_name': 'Agricultural and Biological Sciences'}, 'domain': {'id': 'https://openalex.org/domains/1', 'display_name': 'Life Sciences'}}], 'keywords': [{'id': 'https://openalex.org/keywords/logging', 'display_name': 'Logging', 'score': 0.8833000063896179}, {'id': 'https://openalex.org/keywords/forest-structure', 'display_name': 'Forest structure', 'score': 0.6419000029563904}, {'id': 'https://openalex.org/keywords/microclimate', 'display_name': 'Microclimate', 'score': 0.6047999858856201}, {'id': 'https://openalex.org/keywords/forest-management', 'display_name': 'Forest management', 'score': 0.5939000248908997}, {'id': 'https://openalex.org/keywords/forest-ecology', 'display_name': 'Forest ecology', 'score': 0.5874999761581421}, {'id': 'https://openalex.org/keywords/sustainable-forest-management', 'display_name': 'Sustainable forest management', 'score': 0.5322999954223633}, {'id': 'https://openalex.org/keywords/biodiversity', 'display_name': 'Biodiversity', 'score': 0.5058000087738037}, {'id': 'https://openalex.org/keywords/ecosystem', 'display_name': 'Ecosystem', 'score': 0.4390999972820282}], 'concepts': [{'id': 'https://openalex.org/C125620115', 'wikidata': 'https://www.wikidata.org/wiki/Q845249', 'display_name': 'Logging', 'level': 2, 'score': 0.8833000063896179}, {'id': 'https://openalex.org/C2983469836', 'wikidata': 'https://www.wikidata.org/wiki/Q4421', 'display_name': 'Forest structure', 'level': 3, 'score': 0.6419000029563904}, {'id': 'https://openalex.org/C39432304', 'wikidata': 'https://www.wikidata.org/wiki/Q188847', 'display_name': 'Environmental science', 'level': 0, 'score': 0.633400022983551}, {'id': 'https://openalex.org/C32957820', 'wikidata': 'https://www.wikidata.org/wiki/Q215108', 'display_name': 'Microclimate', 'level': 2, 'score': 0.6047999858856201}, {'id': 'https://openalex.org/C28631016', 'wikidata': 'https://www.wikidata.org/wiki/Q372561', 'display_name': 'Forest management', 'level': 2, 'score': 0.5939000248908997}, {'id': 'https://openalex.org/C73935091', 'wikidata': 'https://www.wikidata.org/wiki/Q2249329', 'display_name': 'Forest ecology', 'level': 3, 'score': 0.5874999761581421}, {'id': 'https://openalex.org/C2775841215', 'wikidata': 'https://www.wikidata.org/wiki/Q47572', 'display_name': 'Sustainable forest management', 'level': 3, 'score': 0.5322999954223633}, {'id': 'https://openalex.org/C54286561', 'wikidata': 'https://www.wikidata.org/wiki/Q397350', 'display_name': 'Agroforestry', 'level': 1, 'score': 0.5109999775886536}, {'id': 'https://openalex.org/C130217890', 'wikidata': 'https://www.wikidata.org/wiki/Q47041', 'display_name': 'Biodiversity', 'level': 2, 'score': 0.5058000087738037}, {'id': 'https://openalex.org/C110872660', 'wikidata': 'https://www.wikidata.org/wiki/Q37813', 'display_name': 'Ecosystem', 'level': 2, 'score': 0.4390999972820282}, {'id': 'https://openalex.org/C2780748813', 'wikidata': 'https://www.wikidata.org/wiki/Q7649683', 'display_name': 'Sustainable management', 'level': 3, 'score': 0.41600000858306885}, {'id': 'https://openalex.org/C129091987', 'wikidata': 'https://www.wikidata.org/wiki/Q5508816', 'display_name': 'Functional ecology', 'level': 3, 'score': 0.3610000014305115}, {'id': 'https://openalex.org/C119249163', 'wikidata': 'https://www.wikidata.org/wiki/Q5442467', 'display_name': 'Felling', 'level': 2, 'score': 0.35760000348091125}, {'id': 'https://openalex.org/C107826830', 'wikidata': 'https://www.wikidata.org/wiki/Q929380', 'display_name': 'Environmental resource management', 'level': 1, 'score': 0.3352000117301941}, {'id': 'https://openalex.org/C2991880734', 'wikidata': 'https://www.wikidata.org/wiki/Q5469188', 'display_name': 'Forest health', 'level': 2, 'score': 0.3237000107765198}, {'id': 'https://openalex.org/C97137747', 'wikidata': 'https://www.wikidata.org/wiki/Q38112', 'display_name': 'Forestry', 'level': 1, 'score': 0.3231000006198883}, {'id': 'https://openalex.org/C18903297', 'wikidata': 'https://www.wikidata.org/wiki/Q7150', 'display_name': 'Ecology', 'level': 1, 'score': 0.3206999897956848}, {'id': 'https://openalex.org/C2777601987', 'wikidata': 'https://www.wikidata.org/wiki/Q5283581', 'display_name': 'Disturbance (geology)', 'level': 2, 'score': 0.2987000048160553}, {'id': 'https://openalex.org/C24037442', 'wikidata': 'https://www.wikidata.org/wiki/Q5469194', 'display_name': 'Forest restoration', 'level': 4, 'score': 0.27970001101493835}, {'id': 'https://openalex.org/C194661718', 'wikidata': 'https://www.wikidata.org/wiki/Q1437217', 'display_name': 'Forest plot', 'level': 3, 'score': 0.2721000015735626}, {'id': 'https://openalex.org/C556436288', 'wikidata': 'https://www.wikidata.org/wiki/Q5333175', 'display_name': 'Ecoforestry', 'level': 5, 'score': 0.27149999141693115}, {'id': 'https://openalex.org/C58941895', 'wikidata': 'https://www.wikidata.org/wiki/Q295865', 'display_name': 'Ecosystem services', 'level': 3, 'score': 0.26489999890327454}], 'mesh': [], 'locations_count': 1, 'locations': [{'id': 'doi:10.70177/jsa.v1i6.1674', 'is_oa': True, 'landing_page_url': 'https://doi.org/10.70177/jsa.v1i6.1674', 'pdf_url': 'https://research.adra.ac.id/index.php/selvicoltura/article/download/1674/1128', 'source': {'id': 'https://openalex.org/S7407059167', 'display_name': 'Journal of Selvicoltura Asean', 'issn_l': '3048-1171', 'issn': ['3048-1171', '3048-1198'], 'is_oa': False, 'is_in_doaj': False, 'is_core': False, 'host_organization': None, 'host_organization_name': None, 'host_organization_lineage': [], 'host_organization_lineage_names': [], 'type': 'journal'}, 'license': 'cc-by-sa', 'license_id': 'https://openalex.org/licenses/cc-by-sa', 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Journal of Selvicoltura Asean', 'raw_type': 'journal-article'}], 'best_oa_location': {'id': 'doi:10.70177/jsa.v1i6.1674', 'is_oa': True, 'landing_page_url': 'https://doi.org/10.70177/jsa.v1i6.1674', 'pdf_url': 'https://research.adra.ac.id/index.php/selvicoltura/article/download/1674/1128', 'source': {'id': 'https://openalex.org/S7407059167', 'display_name': 'Journal of Selvicoltura Asean', 'issn_l': '3048-1171', 'issn': ['3048-1171', '3048-1198'], 'is_oa': False, 'is_in_doaj': False, 'is_core': False, 'host_organization': None, 'host_organization_name': None, 'host_organization_lineage': [], 'host_organization_lineage_names': [], 'type': 'journal'}, 'license': 'cc-by-sa', 'license_id': 'https://openalex.org/licenses/cc-by-sa', 'version': 'publishedVersion', 'is_accepted': True, 'is_published': True, 'raw_source_name': 'Journal of Selvicoltura Asean', 'raw_type': 'journal-article'}, 'sustainable_development_goals': [{'id': 'https://metadata.un.org/sdg/15', 'display_name': 'Life in Land', 'score': 0.6333771347999573}], 'awards': [], 'funders': [], 'has_content': {'grobid_xml': True, 'pdf': True}, 'content_urls': {'pdf': 'https://content.openalex.org/works/W7165396956.pdf', 'grobid_xml': 'https://content.openalex.org/works/W7165396956.grobid-xml'}, 'referenced_works_count': 0, 'referenced_works': [], 'related_works': [], 'abstract_inverted_index': {'Selective': [0], 'logging': [1, 38, 61, 91, 134, 147], 'is': [2], 'a': [3, 24, 51], 'prevalent': [4], 'forest': [5, 19, 47, 56, 94, 141, 156], 'management': [6, 162], 'practice': [7], 'aimed': [8], 'at': [9], 'balancing': [10], 'timber': [11], 'production': [12], 'and': [13, 21, 43, 76, 83, 100, 115, 158, 163, 168], 'conservation.': [14], 'However,': [15], 'its': [16, 152], 'effects': [17, 139], 'on': [18, 39, 71, 140, 155], 'structure': [20, 95, 157], 'function': [22, 159], 'remain': [23], 'topic': [25], 'of': [26, 36, 46, 80, 131], 'significant': [27], 'concern.': [28], 'This': [29], 'study': [30], 'aims': [31], 'to': [32, 59, 64, 104, 165], 'evaluate': [33], 'the': [34, 40, 122, 129], 'impact': [35], 'selective': [37, 60, 90, 146], 'biodiversity,': [41], 'biomass,': [42, 77], 'ecological': [44, 124], 'functions': [45], 'ecosystems.': [48, 142], 'We': [49], 'employed': [50], 'comparative': [52], 'analysis': [53], 'method,': [54], 'where': [55], 'plots': [57], 'subjected': [58], 'were': [62, 69, 118], 'compared': [63], 'undisturbed': [65], 'control': [66], 'plots.': [67], 'Data': [68], 'collected': [70], 'tree': [72, 98], 'species': [73, 101], 'diversity,': [74, 102], 'density,': [75], 'alongside': [78], 'assessments': [79], 'soil': [81, 113], 'health': [82], 'microclimate': [84], 'conditions.': [85], 'Our': [86], 'findings': [87], 'indicate': [88], 'that': [89, 136], 'significantly': [92], 'alters': [93], 'by': [96], 'reducing': [97], 'density': [99], 'leading': [103], 'an': [105], 'overall': [106], 'decline': [107], 'in': [108, 112], 'biomass.': [109], 'Additionally,': [110], 'changes': [111], 'composition': [114], 'moisture': [116], 'levels': [117], 'observed,': [119], 'negatively': [120], 'affecting': [121], "forest's": [123], 'functions.': [125], 'The': [126], 'results': [127], 'underscore': [128], 'importance': [130], 'adopting': [132], 'sustainable': [133], 'practices': [135], 'mitigate': [137], 'adverse': [138], 'In': [143], 'conclusion,': [144], 'while': [145], 'can': [148], 'provide': [149], 'economic': [150], 'benefits,': [151], 'detrimental': [153], 'impacts': [154], 'necessitate': [160], 'careful': [161], 'monitoring': [164], 'preserve': [166], 'biodiversity': [167], 'ecosystem': [169], 'health.': [170]}, 'counts_by_year': [], 'updated_date': '2026-06-22T06:23:43.705686', 'created_date': '2026-06-20T00:00:00'}

we check the length of the new author list, and it is in line with what we would expect to see :)

In [38]:
print(len(authors)) # -> ~7,900 
print(len(works))

7929
18779

In [39]:
list(authors).count(None)

1

looking at the list - we get a bunch of openalex author ids. now need to loop through this entire list, query the author API, then collect useful information about each author from there

In [40]:
print(authors, 10)

{'https://openalex.org/A5102170192', 'https://openalex.org/A5038053101', 'https://openalex.org/A5012451717', 'https://openalex.org/A5023286690', 'https://openalex.org/A5030365370', 'https://openalex.org/A5058193230', 'https://openalex.org/A5113834078', 'https://openalex.org/A5051528851', 'https://openalex.org/A5034377021', 'https://openalex.org/A5052364420', 'https://openalex.org/A5031424991', 'https://openalex.org/A5110631057', 'https://openalex.org/A5032810944', 'https://openalex.org/A5107455662', 'https://openalex.org/A5005480436', 'https://openalex.org/A5088872913', 'https://openalex.org/A5021515928', 'https://openalex.org/A5110711132', 'https://openalex.org/A5037654364', 'https://openalex.org/A5055327388', 'https://openalex.org/A5087695450', 'https://openalex.org/A5114395731', 'https://openalex.org/A5091636310', 'https://openalex.org/A5040749724', 'https://openalex.org/A5037912444', 'https://openalex.org/A5052216983', 'https://openalex.org/A5059801247', 'https://openalex.org/A5022513797', 'https://openalex.org/A5089046130', 'https://openalex.org/A5007626909', 'https://openalex.org/A5077262128', 'https://openalex.org/A5008367537', 'https://openalex.org/A5091020659', 'https://openalex.org/A5003041846', 'https://openalex.org/A5076084094', 'https://openalex.org/A5039284600', 'https://openalex.org/A5041344301', 'https://openalex.org/A5079623570', 'https://openalex.org/A5005912029', 'https://openalex.org/A5119271663', 'https://openalex.org/A5112603217', 'https://openalex.org/A5114026072', 'https://openalex.org/A5119426588', 'https://openalex.org/A5101174812', 'https://openalex.org/A5004269333', 'https://openalex.org/A5100650007', 'https://openalex.org/A5113564764', 'https://openalex.org/A5020559144', 'https://openalex.org/A5051204475', 'https://openalex.org/A5041511169', 'https://openalex.org/A5033109187', 'https://openalex.org/A5054803584', 'https://openalex.org/A5044298370', 'https://openalex.org/A5114824109', 'https://openalex.org/A5064884616', 'https://openalex.org/A5045066589', 'https://openalex.org/A5003964627', 'https://openalex.org/A5077280597', 'https://openalex.org/A5082300920', 'https://openalex.org/A5103939530', 'https://openalex.org/A5079925876', 'https://openalex.org/A5079449017', 'https://openalex.org/A5102349912', 'https://openalex.org/A5007272574', 'https://openalex.org/A5021447806', 'https://openalex.org/A5104064156', 'https://openalex.org/A5055393677', 'https://openalex.org/A5066345561', 'https://openalex.org/A5067119826', 'https://openalex.org/A5033210778', 'https://openalex.org/A5059049052', 'https://openalex.org/A5109739423', 'https://openalex.org/A5101424783', 'https://openalex.org/A5093865061', 'https://openalex.org/A5036880466', 'https://openalex.org/A5031424402', 'https://openalex.org/A5036324257', 'https://openalex.org/A5014407450', 'https://openalex.org/A5108762255', 'https://openalex.org/A5027884634', 'https://openalex.org/A5079650143', 'https://openalex.org/A5018133795', 'https://openalex.org/A5053092720', 'https://openalex.org/A5041150754', 'https://openalex.org/A5112389755', 'https://openalex.org/A5103045136', 'https://openalex.org/A5100444195', 'https://openalex.org/A5032001308', 'https://openalex.org/A5039570945', 'https://openalex.org/A5011155609', 'https://openalex.org/A5013398525', 'https://openalex.org/A5023374069', 'https://openalex.org/A5049614671', 'https://openalex.org/A5084604115', 'https://openalex.org/A5092946635', 'https://openalex.org/A5040246965', 'https://openalex.org/A5064426418', 'https://openalex.org/A5100372143', 'https://openalex.org/A5102131342', 'https://openalex.org/A5012723755', 'https://openalex.org/A5032397465', 'https://openalex.org/A5041145494', 'https://openalex.org/A5005906845', 'https://openalex.org/A5005855234', 'https://openalex.org/A5104126783', 'https://openalex.org/A5060953615', 'https://openalex.org/A5033297012', 'https://openalex.org/A5082733788', 'https://openalex.org/A5039747194', 'https://openalex.org/A5019200453', 'https://openalex.org/A5037354644', 'https://openalex.org/A5016059440', 'https://openalex.org/A5100692639', 'https://openalex.org/A5066747131', 'https://openalex.org/A5112893128', 'https://openalex.org/A5075156839', 'https://openalex.org/A5114180415', 'https://openalex.org/A5095830977', 'https://openalex.org/A5007598416', 'https://openalex.org/A5094361178', 'https://openalex.org/A5095333491', 'https://openalex.org/A5087908955', 'https://openalex.org/A5081793612', 'https://openalex.org/A5101922166', 'https://openalex.org/A5003075400', 'https://openalex.org/A5089317398', 'https://openalex.org/A5029777875', 'https://openalex.org/A5086579269', 'https://openalex.org/A5100422186', 'https://openalex.org/A5055637970', 'https://openalex.org/A5076158895', 'https://openalex.org/A5064661478', 'https://openalex.org/A5101537580', 'https://openalex.org/A5088462108', 'https://openalex.org/A5006522350', 'https://openalex.org/A5103199277', 'https://openalex.org/A5036357557', 'https://openalex.org/A5049909213', 'https://openalex.org/A5086549204', 'https://openalex.org/A5008836455', 'https://openalex.org/A5006408695', 'https://openalex.org/A5053194411', 'https://openalex.org/A5056996700', 'https://openalex.org/A5008114266', 'https://openalex.org/A5069056622', 'https://openalex.org/A5024741401', 'https://openalex.org/A5020949665', 'https://openalex.org/A5001354996', 'https://openalex.org/A5042816631', 'https://openalex.org/A5066094932', 'https://openalex.org/A5087178134', 'https://openalex.org/A5030845033', 'https://openalex.org/A5035794293', 'https://openalex.org/A5019122524', 'https://openalex.org/A5103007812', 'https://openalex.org/A5035429068', 'https://openalex.org/A5069127560', 'https://openalex.org/A5020632236', 'https://openalex.org/A5060116992', 'https://openalex.org/A5014944419', 'https://openalex.org/A5052767087', 'https://openalex.org/A5074913066', 'https://openalex.org/A5066477230', 'https://openalex.org/A5054262141', 'https://openalex.org/A5017211526', 'https://openalex.org/A5101156639', 'https://openalex.org/A5072243347', 'https://openalex.org/A5019451172', 'https://openalex.org/A5052273342', 'https://openalex.org/A5102597674', 'https://openalex.org/A5030786976', 'https://openalex.org/A5075814310', 'https://openalex.org/A5081601519', 'https://openalex.org/A5113548919', 'https://openalex.org/A5087984351', 'https://openalex.org/A5027074850', 'https://openalex.org/A5024935224', 'https://openalex.org/A5022426180', 'https://openalex.org/A5042354088', 'https://openalex.org/A5079485187', 'https://openalex.org/A5070810466', 'https://openalex.org/A5053407441', 'https://openalex.org/A5029865909', 'https://openalex.org/A5112292305', 'https://openalex.org/A5069337333', 'https://openalex.org/A5001518780', 'https://openalex.org/A5102960584', 'https://openalex.org/A5109802582', 'https://openalex.org/A5071128348', 'https://openalex.org/A5073868515', 'https://openalex.org/A5070433914', 'https://openalex.org/A5024389928', 'https://openalex.org/A5039606064', 'https://openalex.org/A5100735888', 'https://openalex.org/A5092552245', 'https://openalex.org/A5029251872', 'https://openalex.org/A5067088799', 'https://openalex.org/A5086697476', 'https://openalex.org/A5084953118', 'https://openalex.org/A5026790575', 'https://openalex.org/A5036115963', 'https://openalex.org/A5007551770', 'https://openalex.org/A5043617083', 'https://openalex.org/A5078869065', 'https://openalex.org/A5040249022', 'https://openalex.org/A5018066720', 'https://openalex.org/A5001839951', 'https://openalex.org/A5091471139', 'https://openalex.org/A5106406020', 'https://openalex.org/A5038197566', 'https://openalex.org/A5012006207', 'https://openalex.org/A5100657865', 'https://openalex.org/A5031192226', 'https://openalex.org/A5005850573', 'https://openalex.org/A5028436579', 'https://openalex.org/A5036867493', 'https://openalex.org/A5025037775', 'https://openalex.org/A5051697024', 'https://openalex.org/A5049775315', 'https://openalex.org/A5026507654', 'https://openalex.org/A5058205892', 'https://openalex.org/A5014594202', 'https://openalex.org/A5067226056', 'https://openalex.org/A5009427142', 'https://openalex.org/A5081124051', 'https://openalex.org/A5058868383', 'https://openalex.org/A5048953831', 'https://openalex.org/A5024761278', 'https://openalex.org/A5027361434', 'https://openalex.org/A5027431667', 'https://openalex.org/A5092582141', 'https://openalex.org/A5096827723', 'https://openalex.org/A5049514975', 'https://openalex.org/A5058715507', 'https://openalex.org/A5081821382', 'https://openalex.org/A5045076444', 'https://openalex.org/A5074222454', 'https://openalex.org/A5091765070', 'https://openalex.org/A5027419806', 'https://openalex.org/A5099361601', 'https://openalex.org/A5054262111', 'https://openalex.org/A5025656770', 'https://openalex.org/A5019633656', 'https://openalex.org/A5044675407', 'https://openalex.org/A5100738417', 'https://openalex.org/A5067195321', 'https://openalex.org/A5105672849', 'https://openalex.org/A5054535416', 'https://openalex.org/A5008831317', 'https://openalex.org/A5067236434', 'https://openalex.org/A5115512232', 'https://openalex.org/A5028233850', 'https://openalex.org/A5011954114', 'https://openalex.org/A5015481958', 'https://openalex.org/A5045982340', 'https://openalex.org/A5065006433', 'https://openalex.org/A5057060792', 'https://openalex.org/A5100339966', 'https://openalex.org/A5040189249', 'https://openalex.org/A5010289223', 'https://openalex.org/A5111378878', 'https://openalex.org/A5065529657', 'https://openalex.org/A5075109570', 'https://openalex.org/A5050825978', 'https://openalex.org/A5035610005', 'https://openalex.org/A5027980650', 'https://openalex.org/A5053703719', 'https://openalex.org/A5074857764', 'https://openalex.org/A5099178243', 'https://openalex.org/A5072684302', 'https://openalex.org/A5085393464', 'https://openalex.org/A5026782519', 'https://openalex.org/A5000418425', 'https://openalex.org/A5004074785', 'https://openalex.org/A5072826315', 'https://openalex.org/A5025790886', 'https://openalex.org/A5073943991', 'https://openalex.org/A5088451688', 'https://openalex.org/A5057652444', 'https://openalex.org/A5056599117', 'https://openalex.org/A5007322964', 'https://openalex.org/A5011091962', 'https://openalex.org/A5018541208', 'https://openalex.org/A5019999144', 'https://openalex.org/A5108740660', 'https://openalex.org/A5086729529', 'https://openalex.org/A5046962992', 'https://openalex.org/A5016388046', 'https://openalex.org/A5003692078', 'https://openalex.org/A5092223217', 'https://openalex.org/A5002474306', 'https://openalex.org/A5023568906', 'https://openalex.org/A5067603887', 'https://openalex.org/A5021842006', 'https://openalex.org/A5053163006', 'https://openalex.org/A5066694182', 'https://openalex.org/A5035711951', 'https://openalex.org/A5031398350', 'https://openalex.org/A5056121536', 'https://openalex.org/A5065602289', 'https://openalex.org/A5055285234', 'https://openalex.org/A5015362089', 'https://openalex.org/A5100336830', 'https://openalex.org/A5043902791', 'https://openalex.org/A5021199535', 'https://openalex.org/A5009347646', 'https://openalex.org/A5066677866', 'https://openalex.org/A5024370092', 'https://openalex.org/A5023601874', 'https://openalex.org/A5041422465', 'https://openalex.org/A5015976716', 'https://openalex.org/A5035509013', 'https://openalex.org/A5016574706', 'https://openalex.org/A5008634207', 'https://openalex.org/A5004356912', 'https://openalex.org/A5109232127', 'https://openalex.org/A5034589539', 'https://openalex.org/A5028857421', 'https://openalex.org/A5051052331', 'https://openalex.org/A5086201180', 'https://openalex.org/A5114111445', 'https://openalex.org/A5052508241', 'https://openalex.org/A5069789969', 'https://openalex.org/A5047036443', 'https://openalex.org/A5003113082', 'https://openalex.org/A5061471342', 'https://openalex.org/A5111056239', 'https://openalex.org/A5101777458', 'https://openalex.org/A5014329725', 'https://openalex.org/A5101365581', 'https://openalex.org/A5109250191', 'https://openalex.org/A5036927304', 'https://openalex.org/A5051437613', 'https://openalex.org/A5087188294', 'https://openalex.org/A5028081842', 'https://openalex.org/A5029471858', 'https://openalex.org/A5000970607', 'https://openalex.org/A5074684602', 'https://openalex.org/A5038524753', 'https://openalex.org/A5034714637', 'https://openalex.org/A5024385871', 'https://openalex.org/A5097218248', 'https://openalex.org/A5066334243', 'https://openalex.org/A5004300155', 'https://openalex.org/A5045544087', 'https://openalex.org/A5051801831', 'https://openalex.org/A5056239091', 'https://openalex.org/A5113360973', 'https://openalex.org/A5053442069', 'https://openalex.org/A5083926877', 'https://openalex.org/A5049537916', 'https://openalex.org/A5086931084', 'https://openalex.org/A5099636000', 'https://openalex.org/A5089796045', 'https://openalex.org/A5030344959', 'https://openalex.org/A5082142520', 'https://openalex.org/A5113114976', 'https://openalex.org/A5041271758', 'https://openalex.org/A5110100857', 'https://openalex.org/A5067935937', 'https://openalex.org/A5047767496', 'https://openalex.org/A5075297650', 'https://openalex.org/A5101734954', 'https://openalex.org/A5102742967', 'https://openalex.org/A5025795348', 'https://openalex.org/A5109634693', 'https://openalex.org/A5086557273', 'https://openalex.org/A5010169014', 'https://openalex.org/A5100692141', 'https://openalex.org/A5071617170', 'https://openalex.org/A5066880338', 'https://openalex.org/A5052748246', 'https://openalex.org/A5094098148', 'https://openalex.org/A5006521692', 'https://openalex.org/A5110847758', 'https://openalex.org/A5085375787', 'https://openalex.org/A5059549026', 'https://openalex.org/A5075775877', 'https://openalex.org/A5080839869', 'https://openalex.org/A5060107382', 'https://openalex.org/A5108574293', 'https://openalex.org/A5072681799', 'https://openalex.org/A5006806369', 'https://openalex.org/A5005530879', 'https://openalex.org/A5078054913', 'https://openalex.org/A5047103464', 'https://openalex.org/A5013868450', 'https://openalex.org/A5031010757', 'https://openalex.org/A5074551350', 'https://openalex.org/A5087323271', 'https://openalex.org/A5114132259', 'https://openalex.org/A5001474761', 'https://openalex.org/A5018611570', 'https://openalex.org/A5053143711', 'https://openalex.org/A5101478789', 'https://openalex.org/A5035463939', 'https://openalex.org/A5037710580', 'https://openalex.org/A5082854012', 'https://openalex.org/A5038828920', 'https://openalex.org/A5049288121', 'https://openalex.org/A5044896588', 'https://openalex.org/A5078121912', 'https://openalex.org/A5041951013', 'https://openalex.org/A5085410716', 'https://openalex.org/A5073382898', 'https://openalex.org/A5033617921', 'https://openalex.org/A5068946677', 'https://openalex.org/A5059056746', 'https://openalex.org/A5066987877', 'https://openalex.org/A5024576121', 'https://openalex.org/A5103132728', 'https://openalex.org/A5008437652', 'https://openalex.org/A5023515660', 'https://openalex.org/A5026991178', 'https://openalex.org/A5021856647', 'https://openalex.org/A5033884494', 'https://openalex.org/A5017301743', 'https://openalex.org/A5068710825', 'https://openalex.org/A5090873433', 'https://openalex.org/A5085759195', 'https://openalex.org/A5043684828', 'https://openalex.org/A5000514429', 'https://openalex.org/A5077741523', 'https://openalex.org/A5002046327', 'https://openalex.org/A5064876624', 'https://openalex.org/A5039402913', 'https://openalex.org/A5019997773', 'https://openalex.org/A5042383701', 'https://openalex.org/A5064718439', 'https://openalex.org/A5059194152', 'https://openalex.org/A5013093027', 'https://openalex.org/A5037459113', 'https://openalex.org/A5095451941', 'https://openalex.org/A5039370835', 'https://openalex.org/A5093837267', 'https://openalex.org/A5018042276', 'https://openalex.org/A5018726467', 'https://openalex.org/A5033057164', 'https://openalex.org/A5110883813', 'https://openalex.org/A5049408362', 'https://openalex.org/A5112957370', 'https://openalex.org/A5100494499', 'https://openalex.org/A5026320810', 'https://openalex.org/A5003703026', 'https://openalex.org/A5060637303', 'https://openalex.org/A5081474134', 'https://openalex.org/A5054619443', 'https://openalex.org/A5012701075', 'https://openalex.org/A5022925223', 'https://openalex.org/A5113204459', 'https://openalex.org/A5109717388', 'https://openalex.org/A5083508850', 'https://openalex.org/A5032471432', 'https://openalex.org/A5084837583', 'https://openalex.org/A5036663902', 'https://openalex.org/A5072752743', 'https://openalex.org/A5083898743', 'https://openalex.org/A5100357241', 'https://openalex.org/A5047939090', 'https://openalex.org/A5070161121', 'https://openalex.org/A5062780706', 'https://openalex.org/A5112569423', 'https://openalex.org/A5035176274', 'https://openalex.org/A5089538097', 'https://openalex.org/A5100750005', 'https://openalex.org/A5113361465', 'https://openalex.org/A5022937855', 'https://openalex.org/A5110335104', 'https://openalex.org/A5010995436', 'https://openalex.org/A5076416027', 'https://openalex.org/A5070861421', 'https://openalex.org/A5024269299', 'https://openalex.org/A5025796629', 'https://openalex.org/A5028860365', 'https://openalex.org/A5033884262', 'https://openalex.org/A5027508220', 'https://openalex.org/A5062588698', 'https://openalex.org/A5071855708', 'https://openalex.org/A5011242778', 'https://openalex.org/A5035385095', 'https://openalex.org/A5104300428', 'https://openalex.org/A5000035333', 'https://openalex.org/A5081425429', 'https://openalex.org/A5100636526', 'https://openalex.org/A5085218094', 'https://openalex.org/A5052851310', 'https://openalex.org/A5102133296', 'https://openalex.org/A5056499449', 'https://openalex.org/A5054088513', 'https://openalex.org/A5046589123', 'https://openalex.org/A5083024953', 'https://openalex.org/A5000170169', 'https://openalex.org/A5062471502', 'https://openalex.org/A5042656235', 'https://openalex.org/A5029642362', 'https://openalex.org/A5074986437', 'https://openalex.org/A5100366888', 'https://openalex.org/A5119409927', 'https://openalex.org/A5047352513', 'https://openalex.org/A5059451258', 'https://openalex.org/A5102732934', 'https://openalex.org/A5103590183', 'https://openalex.org/A5113399058', 'https://openalex.org/A5001082656', 'https://openalex.org/A5037667733', 'https://openalex.org/A5074790423', 'https://openalex.org/A5031745550', 'https://openalex.org/A5071936861', 'https://openalex.org/A5041551850', 'https://openalex.org/A5048991930', 'https://openalex.org/A5046466773', 'https://openalex.org/A5002593878', 'https://openalex.org/A5094180071', 'https://openalex.org/A5047741001', 'https://openalex.org/A5014038622', 'https://openalex.org/A5006397152', 'https://openalex.org/A5095334926', 'https://openalex.org/A5080520469', 'https://openalex.org/A5093577961', 'https://openalex.org/A5000489188', 'https://openalex.org/A5010728482', 'https://openalex.org/A5109262333', 'https://openalex.org/A5101957696', 'https://openalex.org/A5099341999', 'https://openalex.org/A5086331004', 'https://openalex.org/A5066186756', 'https://openalex.org/A5019406573', 'https://openalex.org/A5098579364', 'https://openalex.org/A5010982402', 'https://openalex.org/A5033323748', 'https://openalex.org/A5038246020', 'https://openalex.org/A5001987532', 'https://openalex.org/A5060002954', 'https://openalex.org/A5079541410', 'https://openalex.org/A5102739231', 'https://openalex.org/A5084439785', 'https://openalex.org/A5043373988', 'https://openalex.org/A5014586329', 'https://openalex.org/A5021932807', 'https://openalex.org/A5113131774', 'https://openalex.org/A5010693015', 'https://openalex.org/A5019002958', 'https://openalex.org/A5034372135', 'https://openalex.org/A5040961656', 'https://openalex.org/A5040436347', 'https://openalex.org/A5081292856', 'https://openalex.org/A5113887217', 'https://openalex.org/A5069730099', 'https://openalex.org/A5084708763', 'https://openalex.org/A5047375842', 'https://openalex.org/A5110738906', 'https://openalex.org/A5083231748', 'https://openalex.org/A5101151848', 'https://openalex.org/A5071784157', 'https://openalex.org/A5037094498', 'https://openalex.o

In [41]:
authors_detailed = [] 

for au in tqdm(authors):
    if au != None: 
        id = str(au).lstrip("https://openalex.org/")

        url = f"https://api.openalex.org/authors/{id}"
        results = requests.get(url)

        try:
            auth = results.json()

        except:
            msg = f"Error with ID: {id}"
            print(msg)

        else: 
            try:
                authors_detailed.append(
                    {'OpenAlex ID': id, 
                    'ORCID': auth['orcid'], 
                    'Name': auth['display_name'], 
                    'Alt Names': auth['raw_author_names'], 
                    'Publications': auth['works_count'], 
                    'Citations': auth['cited_by_count'], 
                    'h-index': auth['summary_stats']['h_index'], 
                    'Number of Institutions': len(auth['affiliations']),
                    'Topic': auth['topic_share'][0]['domain']['display_name']}
                )
            except: 
                authors_detailed.append(
                    {'OpenAlex ID': id, 
                    'ORCID': auth['orcid'], 
                    'Name': auth['display_name'], 
                    'Alt Names': auth['raw_author_names'], 
                    'Publications': auth['works_count'], 
                    'Citations': auth['cited_by_count'], 
                    'h-index': auth['summary_stats']['h_index'], 
                    'Number of Institutions': len(auth['affiliations']),
                    'Topic': ''}
                )

authors_detailed = pd.DataFrame(authors_detailed)
authors_detailed

100%|██████████| 7929/7929 [30:37<00:00,  4.32it/s]

,OpenAlex ID,ORCID,Name,Alt Names,Publications,Citations,h-index,Number of Institutions,Topic
0,A5102170192,None,Jeongmee Kim,[Jeongmee Kim],4,10,2,2,Health Sciences
1,A5038053101,None,Nicole Szulc,[Nicole Szulc],1,38,1,2,Life Sciences
2,A5012451717,https://orcid.org/0000-0002-2613-9321,M. Williams,"[M C Williams, M Williams, M. C. S. Williams, ...",73,1696,18,16,Physical Sciences
3,A5023286690,https://orcid.org/0000-0002-1107-9135,Emma Griffiths,"[E Griffiths, E. Griffiths, E.J. Griffiths, Em...",119,9726,31,21,Life Sciences
4,A5030365370,https://orcid.org/0000-0002-9012-4079,Alfons A den Broeder,"[A A Den Broeder, A A d. Broeder, A A den Broe...",353,11851,48,31,Health Sciences
...,...,...,...,...,...,...,...,...,...
7923,A5108220854,None,D. H. C. Wilton,"[D H C Wilton, D Wilton, D. H. C. Wilton, D. H...",65,639,14,8,Physical Sciences
7924,A5022991962,https://orcid.org/0000-0001-7496-3991,Jessica Bouchard,"[Bouchard, Jessica, J. R. Bouchard, J.R. Bouch...",40,400,12,6,Social Sciences
7925,A5000439771,None,Priya Nahal,[Priya Nahal],1,11,1,1,Social Sciences
7926,A5032945153,https://orcid.org/0000-0001-8866-6541,Kirsten Zickfeld,"[K Zickfeld, K. Zickfeld, Kirsten Zickfeld, Zi...",195,8744,47,5,Physical Sciences
7927,A5100700438,https://orcid.org/0000-0003-0774-6502,Jason Wang,"[Carter, Aarynn L., J. J. Wang, J. Wang, J.J. ...",495,6354,40,59,Physical Sciences

In [42]:
auth['topic_share'][0]['domain']['display_name']

'Physical Sciences'

In [43]:
test = pd.DataFrame(works)
test

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,funders,has_content,content_urls,referenced_works_count,referenced_works,related_works,abstract_inverted_index,counts_by_year,updated_date,created_date
0,https://openalex.org/W4288079944,https://doi.org/10.1051/0004-6361/201833910,<i>Planck</i> 2018 results,<i>Planck</i> 2018 results,2020,2020-04-03,{'openalex': 'https://openalex.org/W4288079944...,en,"{'id': 'doi:10.1051/0004-6361/201833910', 'is_...",article,...,"[{'id': 'https://openalex.org/F4320306101', 'd...","{'pdf': True, 'grobid_xml': True}",{'pdf': 'https://content.openalex.org/works/W4...,528,"[https://openalex.org/W1481932901, https://ope...","[https://openalex.org/W2047028841, https://ope...","{'We': [0, 90, 264, 432], 'present': [1], 'cos...","[{'year': 2026, 'cited_by_count': 1149}, {'yea...",2026-06-29T08:53:18.405633,2022-07-28T00:00:00
1,https://openalex.org/W3004480399,https://doi.org/10.1038/s41586-020-1943-3,The repertoire of mutational signatures in hum...,The repertoire of mutational signatures in hum...,2020,2020-02-05,{'openalex': 'https://openalex.org/W3004480399...,en,"{'id': 'doi:10.1038/s41586-020-1943-3', 'is_oa...",article,...,"[{'id': 'https://openalex.org/F4320308349', 'd...","{'pdf': True, 'grobid_xml': True}",{'pdf': 'https://content.openalex.org/works/W3...,66,"[https://openalex.org/W1246381107, https://ope...","[https://openalex.org/W4255048859, https://ope...","{'Abstract': [0], 'Somatic': [1], 'mutations':...","[{'year': 2026, 'cited_by_count': 236}, {'year...",2026-06-29T08:53:18.405633,2025-10-10T00:00:00
2,https://openalex.org/W3006500278,https://doi.org/10.1038/s41586-020-1969-6,Pan-cancer analysis of whole genomes,Pan-cancer analysis of whole genomes,2020,2020-02-05,{'openalex': 'https://openalex.org/W3006500278...,en,"{'id': 'doi:10.1038/s41586-020-1969-6', 'is_oa...",article,...,"[{'id': 'https://openalex.org/F4320311543', 'd...","{'pdf': True, 'grobid_xml': True}",{'pdf': 'https://content.openalex.org/works/W3...,113,"[https://openalex.org/W1517051009, https://ope...","[https://openalex.org/W4391375266, https://ope...","{'Abstract': [0], 'Cancer': [1, 58, 64], 'is':...","[{'year': 2026, 'cited_by_count': 166}, {'year...",2026-06-29T08:53:18.405633,2020-02-24T00:00:00
3,https://openalex.org/W3108936441,https://doi.org/10.1080/15548627.2020.1797280,Guidelines for the use and interpretation of a...,Guidelines for the use and interpretation of a...,2021,2021-01-02,{'openalex': 'https://openalex.org/W3108936441...,en,"{'id': 'doi:10.1080/15548627.2020.1797280', 'i...",article,...,"[{'id': 'https://openalex.org/F4320306127', 'd...","{'pdf': True, 'grobid_xml': False}",{'pdf': 'https://content.openalex.org/works/W3...,4092,"[https://openalex.org/W1919353, https://openal...","[https://openalex.org/W4391375266, https://ope...","{'autophagic': [0], 'responses.': [1], 'Here,'...","[{'year': 2026, 'cited_by_count': 213}, {'year...",2026-06-29T08:53:18.405633,2020-12-07T00:00:00
4,https://openalex.org/W3045910546,https://doi.org/10.1038/s41586-020-2493-4,Expanded encyclopaedias of DNA elements in the...,Expanded encyclopaedias of DNA elements in the...,2020,2020-07-29,{'openalex': 'https://openalex.org/W3045910546...,en,"{'id': 'doi:10.1038/s41586-020-2493-4', 'is_oa...",article,...,"[{'id': 'https://openalex.org/F4320332161', 'd...","{'pdf': True, 'grobid_xml': True}",{'pdf': 'https://content.openalex.org/works/W3...,73,"[https://openalex.org/W1544691147, https://ope...","[https://openalex.org/W3160486573, https://ope...","{'Abstract': [0], 'The': [1], 'human': [2, 115...","[{'year': 2026, 'cited_by_count': 209}, {'year...",2026-06-28T08:01:55.173337,2020-08-03T00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18774,https://openalex.org/W7164925562,https://doi.org/10.1080/17153379.2024.12558497,The Industrial Ephemeral: Labor and Love in In...,The Industrial Ephemeral: Labor and Love in In...,2024,2024-06-01,{'openalex': 'https://openalex.org/W7164925562...,en,"{'id': 'doi:10.1080/17153379.2024.12558497', '...",article,...,[],"{'grobid_xml': False, 'pdf': False}",None,0,[],[],None,[],2026-06-18T08:10:14.011955,2026-06-17T00:00:00
18775,https://openalex.org/W7164929030,https://doi.org/10.1080/17153379.2020.12559653,Paradoxes of the Popular: Crowd Politics in Ba...,Paradoxes of the Popular: Crowd Politics in Ba...,2020,2020-09-01,{'openalex': 'https://openalex.org/W7164929030...,en,"{'id': 'doi:10.1080/17153379.2020.12559653', '...",article,...,[],"{'grobid_xml': False, 'pdf': False}",None,0,[],[],None,[],2026-06-26T08:34:08.712188,2026-06-17T00:00:00
18776,https://openalex.org/W7164930168,https://doi.org/10.1080/17153379.2022.12558206,Hegemonic Mimicry: Korean Popular Culture of t...,Hegemonic Mimicry: Korean Popular Culture of t...,2022,2022-12-01,{'openalex': 'https://openalex.org/W7164930168...,en,"{'id': 'doi:10.1080/17153379.2022.12558206', '...",article,...,[],"{'grobid_xml': False, 'pdf': False}",None,0,[],[],None,[],2026-06-18T08:10:14.011955,2026-06-17T00:00:00
18777,https://openalex.org/W7164948495,https://doi.org/10.1080/17153379.2023.12558380,Seeking Western Men: Email-Order Brides under ...,Seeking Western Men: Email-Order Brides under ...,2023,2023-12-01,{'openalex': 'https://openalex.org/W7164948495...,en,"{'id': 'doi:10.1080/17153379.2023.12558380', '...",article,...,[],"{'grobid_xml': False, 'pdf': False}",None,0,[],[],None,[],2026-06-18T08:10:14.011955,2026-06-17T00:00:00
18778,https://openalex.org/W7165396956,https://doi.org/10.70177/jsa.v1i6.1674,The Impact of Selective Logging on Forest Stru...,The Impact of Selective Logging on Forest Stru...,2024,2024-12-26,{'openalex': 'https://openalex.org/W7165396956...,None,"{'id': 'doi:10.70177/jsa.v1i6.1674', 'is_oa': ...",article,...,[],"{'grobid_xml': True, 'pdf': True}",{'pdf': 'https://content.openalex.org/works/W7...,0,[],[],"{'Selective': [0], 'logging': [1, 38, 61, 91, ...",[],2026-06-22T06:23:43.705686,2026-06-20T00:00:00

In [44]:
pd.DataFrame(authors_detailed).to_csv('./OA_auths_20-24.csv', index = False)
pd.DataFrame(works).to_csv('./OA_works_20-24.csv', index = False)

In [45]:
works = pd.DataFrame(works)
sum(works['cited_by_count'])

316165

In [47]:
print(len(works))

18779